### ISSUE TITLE
duration variable in notification service is not working as intended

### ISSUE THREAD

**Issue by shaulbarlev** [LAB02-Research/HASS.Agent-Integration#16]
Hi,
I'm trying to make a notification appear for more than the default time, essentially to not fade until dismissed. Here is the script I run:
```
alias: Dad Shush
sequence:
  - service: notify.avnerpc
    data:
      message: Thank you
      title: Please keep your voice down
      data:
        duration: 500
        image: >-
          https://media2.giphy.com/media/rdAeOA3mfXomQ/giphy.gif?cid=ecf05e470wminowgn4nov7b90f8zlouyx7yh0mqqrwya1uw7&rid=giphy.gif&ct=g
        actions:
          - action: OK
            title: "OK"
mode: single
```

The notification appears for only 5 seconds.
Thanks
